# Generated by Django 4.2.7 on 2023-11-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_student_activity_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.activity')),
            ],
        ),
    ]
