# Generated by Django 4.2.7 on 2023-11-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_studentpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpoints',
            name='activity',
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.student'),
        ),
    ]
