# Generated by Django 4.2.7 on 2023-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_studentpoints_activity_studentpoints_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='student',
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ManyToManyField(to='categories.student'),
        ),
    ]
