# Generated by Django 4.2.7 on 2023-11-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_activity_student_activity_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentpoints',
            name='student',
        ),
    ]
