# Generated by Django 4.2.7 on 2023-11-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_rename_student_activity_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpoints',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.student'),
        ),
    ]
