# Generated by Django 4.2.7 on 2023-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redeemaward',
            options={'ordering': ['-date_redeemed']},
        ),
        migrations.AddField(
            model_name='awarditem',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
