# Generated by Django 4.2.7 on 2023-11-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_redeemaward_options_awarditem_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemaward',
            name='select_award',
            field=models.ForeignKey(limit_choices_to={'available__gt': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.awarditem'),
        ),
    ]
