# Generated by Django 4.2.7 on 2023-12-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_redeemaward_select_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(blank=True, choices=[('school1', 'School 1'), ('school2', 'School 2')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='redeemaward',
            name='select_award',
            field=models.ForeignKey(limit_choices_to={'units__gt': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.awarditem'),
        ),
        migrations.AddField(
            model_name='awarditem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='pointcategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='redeemaward',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school'),
        ),
    ]
