# Generated by Django 4.2.7 on 2023-12-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_redeemaward_select_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemaward',
            name='select_award',
            field=models.ForeignKey(limit_choices_to={'units__gt': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.awarditem'),
        ),
    ]
