# Generated by Django 4.2.7 on 2023-12-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_school_alter_redeemaward_select_award_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
    ]
